// NORIA CAPABILITY MAP — the full capability surface of a leading general-purpose AI system, and Noria's progress toward every part of it.
//
// This map MEASURES progress. It does not define the limits of Noria. Every entry is a TARGET: something Noria is meant to be able to do.
// A capability that is not built yet is an engineering gap to close, never evidence that Noria "cannot" do that kind of work. So the state of an
// entry is always written as target -> implemented -> verified, together with WHAT IS MISSING (infrastructure, a provider, an integration, the
// owner's authorisation, production verification, or a design), and the NEXT engineering step.
//
// Implemented / verified are NEVER stored here. They are derived from the capability registry (agent/families.js), which holds the evidence rules,
// so this map cannot claim more than the registry allows. An entry with no registry row yet is "unassessed": not "none", and not "yes".
//
// Kept apart on purpose (they are different facts):
//   target         Noria is meant to be able to do this                        (always true)
//   implemented    what has been built                                          (from the registry)
//   verified       what has been tested for real                                (from the registry)
//   available      usable by a person today                                     (derived: implemented partial/yes)
//   connected      a live tool or provider is wired to it                       (derived from the tool registry)
//   authorised     Noria is permitted to perform it                             (per entry: read-only authorised / needs approval / n/a)
//   blocked_by     what stands between today and "verified": infrastructure | provider | integration | authorisation | verification | design | none

export const BLOCKERS = {
  none: "", infrastructure: "infrastructure required", provider: "a data or service provider is needed", integration: "integration still to build",
  authorisation: "needs the owner's authorisation before it can be enabled", verification: "built; needs production verification", design: "design still to do",
};

// E(id, name, what leading systems do, needs{...}, blocker, next step, linked registry ids, authorisation)
const E = (id, name, reference, needs, blocker, next, families = [], authz = "n/a") => ({ id, name, target: true, reference, needs: { architecture: [], tools: [], runtimes: [], providers: [], permissions: [], ...needs }, blocker, next, families, authorisation: authz });
const RO = "read-only authorised", APPROVAL = "approval required (acting tools are not yet authorised)", NA = "n/a (no effect outside Noria)";

export const GROUPS = [
  { id: "reasoning", name: "Reasoning and knowledge", entries: [
    E("reasoning-general", "General reasoning and problem solving", "Multi-step reasoning across most subjects, planning, judgement, explanation.", { architecture: ["reasoning model layer", "verification of checkable claims"], providers: ["LLM providers (free tiers)"] }, "verification", "Measure reasoning on unseen tasks beyond the current benchmark; add a form/logic verifier.", ["reasoning", "uncertainty"], NA),
    E("reasoning-math", "Mathematical reasoning", "Symbolic and numeric maths, step-by-step proofs, exact arithmetic via tools.", { tools: ["calc.math", "code.run (sandbox)"], runtimes: ["safe calculator", "code sandbox"] }, "infrastructure", "Sandbox for symbolic/numeric work beyond the safe calculator.", ["reasoning", "code-run"], NA),
    E("long-context", "Long-context understanding", "Reading and reasoning over very long documents or many files at once.", { architecture: ["chunking + retrieval", "hierarchical summarisation"], tools: ["knowledge.search"] }, "verification", "Production-verify hybrid retrieval; add map-reduce summarisation for whole-document tasks.", ["lt-knowledge", "doc-multi"], NA),
    E("science-research", "Scientific and academic research", "Literature search, reading papers, extracting methods and results with citations.", { providers: ["academic indexes (arXiv, PubMed, OpenAlex, Crossref: free APIs exist)"], tools: ["web.search", "doc.read"] }, "provider", "Connect free scholarly indexes and add paper-level citation verification.", ["academic", "citation"], RO),
    E("education", "Education and tutoring", "Adaptive explanations, worked examples, quizzes, study plans, feedback.", { architecture: ["learner memory", "exercise generation + checking"], tools: ["calc.math", "code.run (sandbox)"] }, "design", "Design a learner model on top of project memory; verify exercises with tools.", [], NA),
    E("translation", "Translation and multilingual work", "Translate and write in many languages, keep terminology and tone.", { architecture: ["language detection", "terminology memory"], providers: ["LLM providers"] }, "verification", "Measure translation quality on real African-language and European-language tasks.", [], NA),
    E("uncertainty-handling", "Uncertainty, refusal to guess, contradiction handling", "Says when unsure, cites, surfaces conflicting sources.", { architecture: ["reality layer verdicts", "contradiction detection"] }, "integration", "Drive chat answers from verdicts (needs the owner's tested rollout); add contradiction detection across documents.", ["uncertainty", "contradiction", "r-nostate", "r-conflict"], NA),
  ] },
  { id: "research", name: "Research and real-time information", entries: [
    E("web-research", "Current web research", "Search, read pages, synthesise with citations.", { tools: ["web.search", "web.read"], providers: ["a web search API (Tavily out of allowance; Brave key not set; Wikipedia + news feeds live)"] }, "provider", "Add a second open-web search provider and keys (owner-supplied) so coverage is not degraded. web.read (reading a full page, not just a search snippet) is verified live in production (11 of 11 against the real internet, including real SSRF and DNS-rebinding refusals); a live redirect-chain proof and real oversized-body truncation remain unmeasured.", ["web-research", "temporal", "web-page-read"], RO),
    E("deep-research", "Deep research reports", "Plan sub-questions, read many sources, produce a cited report.", { tools: ["research.deep", "web.search"], architecture: ["task graph", "citation verification"] }, "verification", "Run deep research as a persisted task graph objective; verify citations per claim.", ["deep-research", "citation"], RO),
    E("fact-verification", "Multi-source fact verification", "Cross-checks claims and states confidence.", { architecture: ["reality layer"], tools: ["fx.rate", "crypto.price", "weather.get"] }, "integration", "Extend verified adapters to more domains; connect the chat to the router (owner decision).", ["r-authority", "r-passport", "r-conflict", "r-freshness", "r-graph", "r-router"], RO),
    E("news-monitoring", "News and topic monitoring", "Track a topic over time and report changes.", { architecture: ["scheduler", "background runtime", "notifications"], tools: ["web.search"] }, "authorisation", "Background execution exists as disabled code; needs the owner's authorisation, a scheduler and notification channel.", ["longitudinal", "lt-background"], RO),
    E("rt-fx", "Exchange rates", "Live and daily currency rates with sources.", { tools: ["fx.rate"], providers: ["ECB reference", "open.er-api", "currency-api"] }, "none", "Add an intraday source if a free one exists.", ["r-fx"], RO),
    E("rt-crypto", "Cryptocurrency prices", "Live spot prices with the exchanges compared.", { tools: ["crypto.price"], providers: ["Coinbase", "Kraken", "Binance", "CoinGecko"] }, "none", "Widen the list of assets.", ["r-crypto"], RO),
    E("rt-weather", "Weather", "Current conditions and forecast for a place.", { tools: ["weather.get"], providers: ["MET Norway", "Open-Meteo"] }, "none", "Add forecast verification, not only current temperature.", ["r-weather"], RO),
    E("rt-flights", "Flight status", "Live delays, gates, schedules.", { providers: ["an aviation data provider (some free tiers exist, e.g. OpenSky for positions; delay data usually needs a licence)"], tools: ["flights.status (to build)"], architecture: ["entity resolution (airports, flights)"] }, "provider", "Select and connect a flight-data provider; build the flights.status adapter through the reality layer.", ["r-flights"], RO),
    E("rt-traffic", "Traffic and routing", "Live traffic, ETAs, directions.", { providers: ["a maps/traffic provider (OSRM/OpenRouteService free tiers give routes; live traffic usually needs a licence)"], tools: ["maps.route (to build)"] }, "provider", "Connect a routing provider first (free), then live traffic if a source is found.", ["r-traffic"], RO),
    E("rt-markets", "Stock and market data", "Quotes, charts, filings.", { providers: ["a market-data provider (delayed quotes are often free; real-time is licensed)", "SEC EDGAR for filings (free)"], tools: ["markets.quote (to build)"] }, "provider", "Connect delayed quotes and EDGAR filings; state delay in every answer.", ["r-markets"], RO),
    E("rt-government", "Government, legislation and immigration information", "Official rules, notices, appointment systems.", { providers: ["official government/legislation sites and APIs per country"], architecture: ["source lock", "per-country adapters"] }, "provider", "Start with one country's official legislation/immigration source and build the adapter through the source lock.", ["r-visa", "r-law", "r-lock"], RO),
    E("rt-company", "Company and business information", "Registries, filings, ownership.", { providers: ["OpenCorporates / national registries (some free)"], architecture: ["entity resolution (organisations)"] }, "provider", "Connect a registry and extend organisation entity resolution.", ["r-registry", "r-entity"], RO),
    E("rt-travel", "Travel planning and logistics", "Itineraries, prices, visa checks, maps.", { tools: ["maps.route", "flights.status", "weather.get", "fx.rate"], architecture: ["task graph"] }, "provider", "Compose weather, rates and routing now; add flights and lodging providers.", ["prod-travel"], RO),
    E("shopping-research", "Shopping and product research", "Compare products, prices, reviews.", { providers: ["product/price sources", "web search"], tools: ["web.search"] }, "provider", "Add product-price sources; verify claims across sellers.", [], RO),
    E("maps-location", "Maps and location tasks", "Places, distances, directions, geocoding.", { providers: ["OpenStreetMap-based services (free)"], tools: ["maps.route", "maps.geocode (to build)"] }, "provider", "Connect a free routing/geocoding provider through the reality layer.", [], RO),
  ] },
  { id: "documents", name: "Documents, files and knowledge", entries: [
    E("docs-read", "PDFs and documents", "Read PDFs, Word, slides, text with page references.", { tools: ["doc.read"], runtimes: ["browser parsers"] }, "verification", "Scanned-PDF support and production verification on real documents.", ["doc-read"], RO),
    E("docs-vision", "OCR and document vision", "Read scans, photos of documents, tables, handwriting.", { tools: ["vision.describe", "ocr.read (to build)"], providers: ["vision models", "OCR engine"] }, "infrastructure", "Add a server or in-browser OCR engine; verify on real scans.", ["doc-ocr", "vision"], RO),
    E("docs-analysis", "File analysis across many documents", "Compare, extract, reconcile across a folder of files.", { architecture: ["knowledge base", "task graph"], tools: ["knowledge.search"] }, "verification", "Production-verify meaning search (Cloudflare embedding allowance); add cross-document comparison tasks.", ["doc-multi", "lt-knowledge"], RO),
    E("docs-structured", "Structured documents, forms, contracts, invoices", "Extract fields into structured data, fill forms.", { architecture: ["schema extraction", "validation"], tools: ["doc.read"] }, "design", "Schema-first extraction with validation and human review.", ["doc-forms"], NA),
    E("docs-generate", "Writing and exporting documents (Word, Excel, PowerPoint, PDF)", "Produce finished files.", { tools: ["doc.export"], runtimes: ["browser libraries"] }, "verification", "Automated tests for exports and offline library bundles.", ["doc-generate", "biz-docs"], NA),
    E("docs-convert", "File conversion", "Convert between formats.", { tools: ["convert.file (to build)"], runtimes: ["browser or sandbox"] }, "infrastructure", "Build conversion in the sandbox and browser libraries.", [], NA),
    E("knowledge-base", "Personal and team knowledge bases", "Search your own documents with citations.", { tools: ["knowledge.search"], architecture: ["hybrid retrieval"] }, "verification", "Production-verify meaning search; add a screen for adding/removing documents.", ["lt-knowledge"], RO),
  ] },
  { id: "data", name: "Data, analysis and visualisation", entries: [
    E("data-spreadsheets", "Spreadsheets and tables", "Analyse CSV/Excel: totals, groups, correlations.", { tools: ["data.query"], runtimes: ["browser engine"] }, "verification", "More production tests on messy real spreadsheets.", ["data-tables", "data-stats"], NA),
    E("data-viz", "Data visualisation", "Charts and dashboards from data.", { tools: ["chart.draw"], runtimes: ["browser"] }, "verification", "Automated chart tests; dashboard artifacts.", ["data-viz"], NA),
    E("data-sql", "SQL and databases", "Query and reason over databases the person connects.", { tools: ["db.query (to build)"], providers: ["the person's database"], permissions: ["read-only credentials, individually authorised"] }, "authorisation", "Build a read-only connector; each database individually authorised.", ["data-sql"], APPROVAL),
    E("data-forecast", "Forecasting and statistics", "Trends, forecasts, statistical tests.", { tools: ["code.run (sandbox)"], runtimes: ["code sandbox"] }, "infrastructure", "Needs the sandbox with a numeric library.", ["data-forecast"], NA),
    E("data-python", "Data science in Python", "Pandas-style analysis in a notebook-like environment.", { runtimes: ["Python in a sandbox (e.g. WebAssembly)"] }, "infrastructure", "Python runtime in the sandbox after the JavaScript one is verified.", ["code-run"], NA),
  ] },
  { id: "coding", name: "Coding and software engineering", entries: [
    E("code-write", "Writing code", "Write, explain and refactor code in many languages.", { providers: ["LLM providers"], architecture: ["execution feedback loop"] }, "verification", "Close the loop: run generated code in the sandbox and use the results.", ["code-write"], NA),
    E("code-execute", "Code execution (one capability, many isolated runtimes)", "Run code, run tests, report real output; the same tool whichever runtime executes it.", { runtimes: ["browser JavaScript sandbox (built)", "browser Python/WebAssembly", "isolated server Python / JavaScript"], tools: ["code.run"], architecture: ["execution policy chooses the runtime", "authority levels: sealed compute vs everything outside"] }, "verification", "Production-verify the browser JavaScript runtime with the owner check pages; add the Python runtime; add a server-side runtime behind the same code.run.", ["code-run", "code-exec-js"], "sealed sandbox authorised (no per-run approval); everything outside the boundary needs its own approval"),
    E("code-exec-py", "Sandboxed Python execution", "Python for data analysis, science, maths and engineering.", { runtimes: ["Python compiled to WebAssembly inside the same sealed boundary"], providers: ["the Pyodide distribution (owner-approved, downloaded, hash-verified against the npm registry, hosted on this site)"], tools: ["code.run"] }, "integration", "Run a data-analysis objective through the task graph in Python (as already done in JavaScript), then verify it in production; add scientific/numeric packages if a way to fetch and hash-verify them is found.", ["code-exec-py"], "sealed sandbox authorised"),
    E("code-data-analysis", "Data analysis through code (files in, verified tables, reports and charts out)", "Read a CSV, write analysis code, run it, verify the numbers, produce tables and charts, explain the result.", { tools: ["code.run", "artifact.write", "chart.draw"], architecture: ["task graph", "independent cross-checks", "artifacts"] }, "verification", "Run on real customer files; measure model-written analysis code; add Python and numeric libraries.", ["code-data-analysis"], "sealed sandbox authorised"),
    E("code-testing", "Code testing and debugging loops", "Write code, run tests, read the failures, fix, rerun.", { tools: ["code.run"], architecture: ["control loop", "replanning"] }, "verification", "Measure fixes written by a real model on unseen failing tests.", ["code-testing"], "sealed sandbox authorised"),
    E("code-server-isolated", "Server-side isolated execution (enforced memory, CPU and time)", "Heavier or longer computations than a browser can bound.", { runtimes: ["an isolated server execution service"], architecture: ["same code.run capability", "execution policy prefers it for heavy work"] }, "infrastructure", "Choose and build an isolated execution service with enforced limits behind code.run.", ["code-server-isolated"], "sealed boundary applies; everything outside needs approval"),
    E("code-debug", "Debugging", "Reproduce, isolate and fix defects using real execution.", { runtimes: ["sandbox"], architecture: ["task graph"] }, "infrastructure", "Depends on code execution.", ["code-debug"], NA),
    E("code-repo", "Repository work", "Read a repository, make changes across files, run tests, open pull requests.", { providers: ["Git hosting API (GitHub free)"], runtimes: ["sandbox with a filesystem"], permissions: ["repository access, individually authorised"] }, "authorisation", "Read-only repository reading first; writing needs authorisation and a sandbox with a filesystem.", ["code-repo"], APPROVAL),
    E("code-security", "Security review", "Find vulnerabilities in code and dependencies.", { runtimes: ["sandbox"], providers: ["advisory databases (OSV: free)"] }, "infrastructure", "After repository reading; use OSV for dependency advisories.", ["code-security"], NA),
    E("app-building", "Building web apps and tools", "Generate and preview working apps.", { runtimes: ["sandboxed preview"], tools: ["code.run"] }, "infrastructure", "Sandboxed preview of generated pages.", ["create-web"], NA),
  ] },
  { id: "computer", name: "Web browsing and computer use", entries: [
    E("browse-read", "Web browsing and reading pages", "Open pages, read, follow links, extract.", { runtimes: ["remote/headless browser or an in-browser fetch proxy"], tools: ["browser.read (to build)"] }, "infrastructure", "Build a page-reading tool with strict read-only rules.", ["browser-op"], RO),
    E("browse-act", "Web interaction, forms and websites", "Fill forms, click, log in, complete purchases where authorised.", { runtimes: ["browser automation runtime"], permissions: ["per-site authorisation", "human approval for irreversible actions"] }, "authorisation", "Build after read-only browsing; every acting step behind approval.", ["browser-op"], APPROVAL),
    E("computer-use", "Computer and browser operation (screen, mouse, keyboard)", "Operate graphical applications from screenshots.", { runtimes: ["sandboxed desktop or browser", "vision model"], permissions: ["explicit authorisation", "approval gates"] }, "infrastructure", "Long-horizon target: needs a sandboxed desktop and a strong vision model.", ["browser-op", "vision"], APPROVAL),
  ] },
  { id: "multimodal", name: "Multimodal understanding and creation", entries: [
    E("image-understanding", "Image understanding", "Describe, read and reason about images.", { tools: ["vision.describe"], providers: ["vision models"] }, "verification", "Automated tests with real images; daily allowance planning.", ["vision"], RO),
    E("image-generation", "Image generation", "Create images from descriptions.", { tools: ["image.generate"], providers: ["Workers AI image models (daily allowance)"] }, "provider", "Add a second image provider and an allowance budget.", ["create-image"], RO),
    E("image-editing", "Image editing", "Edit, extend, remove, restyle parts of images.", { providers: ["an image-editing model"], tools: ["image.edit (to build)"] }, "provider", "Select an editing model and build the tool.", [], RO),
    E("audio-understanding", "Audio understanding and transcription", "Transcribe and reason over speech and audio.", { providers: ["speech-to-text (in-browser or provider)"], tools: ["audio.transcribe (to build)"] }, "verification", "Speech input exists in the app; verify accuracy and add file transcription.", ["speech"], RO),
    E("audio-generation", "Speech and audio generation", "Natural voice, music and sound.", { tools: ["speech.speak"], providers: ["TTS providers"] }, "verification", "Verify voice quality/latency; music generation is a separate target.", ["speech"], RO),
    E("voice-conversation", "Real-time voice conversation", "Hands-free spoken dialogue.", { architecture: ["streaming speech in/out"], providers: ["speech models"] }, "verification", "Measure latency and turn-taking on real devices.", ["speech"], NA),
    E("video", "Video understanding and generation", "Summarise videos; generate clips.", { providers: ["video models (few free options)"], runtimes: ["frame extraction"] }, "provider", "Frame-based understanding first; generation when a provider is available.", ["video"], NA),
    E("visual-reasoning", "Charts, diagrams and visual reasoning", "Read and reason about charts, diagrams, screenshots.", { providers: ["vision models"], tools: ["vision.describe"] }, "verification", "Build a test set of real charts.", ["visual-reasoning"], NA),
    E("creative", "Creative writing and content generation", "Stories, scripts, marketing copy, product descriptions.", { providers: ["LLM providers"] }, "verification", "Style consistency and plagiarism/originality checks.", ["create-text"], NA),
    E("presentations", "Presentations", "Structured slide decks with speaker notes.", { tools: ["doc.export"], architecture: ["structured outlines"] }, "verification", "Automated export tests; design templates.", ["create-slides"], NA),
    E("research-reports", "Research reports", "Long cited reports and briefs.", { tools: ["research.deep"], architecture: ["task graph", "citation verification"] }, "verification", "Persist as a task-graph objective with artifacts.", ["deep-research", "biz-research"], NA),
  ] },
  { id: "business", name: "Business and productivity", entries: [
    E("business-analysis", "Business analysis", "Market, competitor and financial analysis with sources.", { tools: ["web.search", "data.query", "research.deep"], architecture: ["reality layer"] }, "verification", "Real business objectives as generalisation tests.", ["biz-research", "biz-finance"], RO),
    E("business-workflows", "Financial and business workflows", "Invoices, budgets, reports, reconciliations.", { architecture: ["task graph", "documents", "connectors"], permissions: ["accounting connectors, individually authorised"] }, "integration", "Start with document-based workflows; connectors need authorisation.", ["biz-docs", "biz-finance", "biz-ops"], APPROVAL),
    E("email", "Email", "Read, draft, triage and send email.", { providers: ["Gmail/Outlook APIs (OAuth)"], permissions: ["read scopes first; send needs approval"] }, "authorisation", "Read-only connector first; sending only with per-message approval.", ["prod-calendar-email"], APPROVAL),
    E("calendar", "Calendar", "Read, schedule and reschedule events.", { providers: ["Google/Outlook Calendar APIs (OAuth)"], permissions: ["read first; changes need approval"] }, "authorisation", "Read-only first; each change approved.", ["prod-calendar-email"], APPROVAL),
    E("contacts", "Contacts", "Look up, add and manage contacts across services.", { providers: ["Google/Microsoft contacts APIs"], permissions: ["read scope"] }, "authorisation", "Read-only connector.", [], APPROVAL),
    E("cloud-files", "Cloud storage and files", "Read/organise files in Drive/OneDrive/Dropbox.", { providers: ["Drive/OneDrive/Dropbox APIs (OAuth)"], permissions: ["read first; writes approved"] }, "authorisation", "Read-only connector; writes per action.", [], APPROVAL),
    E("personal-productivity", "Personal productivity: tasks, notes, planning", "Task lists, reminders, planning across projects.", { architecture: ["task graph", "project memory", "notifications"] }, "integration", "Project screen exists (observation); add task creation and reminders.", ["prod-projects", "lt-project", "lt-screen"], NA),
    E("notifications", "Notifications and alerts", "Tell the person when something needs them or finishes.", { providers: ["web push / email (Brevo already used for resets)"], architecture: ["event triggers"] }, "integration", "Web push and email notifications from task-graph events (approval needed, completed).", [], "per-channel opt-in"),
    E("collaboration", "Collaboration and shared workspaces", "Share projects, comment, co-edit.", { architecture: ["permissions model", "shared projects", "activity feed"] }, "design", "Shared-project permission model on top of the per-user isolation.", [], NA),
  ] },
  { id: "agentic", name: "Agentic execution and long-running work", entries: [
    E("agent-planning", "Agentic workflows and autonomous planning", "Turn an objective into a plan and adapt it.", { architecture: ["planner", "task graph", "control loop"] }, "verification", "Measure on unseen objectives; real-model replanning measurement (needs a Pro code).", ["agent-plan", "decompose", "lt-auto-revise", "lt-retry-replan"], NA),
    E("agent-execution", "Multi-step execution", "Run steps in parallel/sequence with retries.", { architecture: ["executor", "gates", "runners"], tools: ["registry tools"] }, "verification", "More real tools; production run of long objectives.", ["agent-exec-seq", "agent-recovery"], RO),
    E("long-running", "Long-running projects", "Objectives that span sessions, pause and resume.", { architecture: ["persistent task graph", "checkpoints"] }, "verification", "Screen and background continuation.", ["lt-project", "lt-graph", "lt-resume", "lt-pause-resume"], NA),
    E("background-tasks", "Background and scheduled work", "Continue without the screen open; run on a schedule.", { architecture: ["scheduler", "server-side runner"], providers: ["Cloudflare cron (exists)"] }, "authorisation", "Built and disabled; needs the owner's authorisation, a per-objective opt-in and budgets.", ["background", "lt-background", "lt-continue"], "owner authorisation required"),
    E("monitoring", "Monitoring and alerts", "Watch a condition and act or notify when it changes.", { architecture: ["scheduler", "reality layer", "notifications"] }, "authorisation", "Depends on background execution and notifications.", ["longitudinal"], RO),
    E("automation", "Workflow automation", "Recurring multi-step workflows.", { architecture: ["task graph templates", "scheduler", "connectors"] }, "integration", "Reusable objective templates.", ["automation"], APPROVAL),
    E("multi-agent", "Multi-agent orchestration", "Specialised agents cooperating on one objective.", { architecture: ["task graph with roles", "shared artifacts"] }, "design", "Roles as task-graph attributes.", [], NA),
    E("human-approval", "Human approval when authority is required", "Ask before consequential actions.", { architecture: ["approval gates", "approval UI"] }, "integration", "Approval controls on the project screen (currently observation only).", ["agent-approval"], "the approval itself"),
    E("recovery", "Recovery from failure", "Retry, replan, ask, stop; never repeat an action blindly.", { architecture: ["control loop"] }, "verification", "Real-model replanning measurement.", ["agent-recovery", "lt-retry-replan", "lt-preserve"], NA),
    E("real-world-actions", "Real-world actions where authorised", "Send, book, buy, file, publish on the person's behalf.", { architecture: ["connectors", "approval gates", "idempotency", "audit"], permissions: ["each connector and each action class individually authorised in writing"] }, "authorisation", "No acting tool is authorised. Each is enabled only after the owner sees its architecture, live results, side-effect audit and tests.", ["agent-approval"], APPROVAL),
  ] },
  { id: "memory", name: "Memory, artifacts and context", entries: [
    E("memory-persistent", "Persistent personal memory", "Remembers preferences and facts, viewable and deletable.", { architecture: ["memory store", "consent + deletion"] }, "verification", "Account-level memory sync (device-only today).", ["prod-memory"], "per-item consent"),
    E("memory-project", "Project memory", "Facts and decisions for the length of a project.", { architecture: ["project store"] }, "verification", "Memory editing from the screen.", ["lt-memory"], NA),
    E("artifacts", "Artifacts (documents, datasets, results) passed between steps", "Versioned outputs that later steps and people can use.", { architecture: ["artifact store"], tools: ["artifact.write", "artifact.read"] }, "verification", "Binary artifacts and export.", ["lt-artifacts"], NA),
    E("history-audit", "Tamper-evident history and audit", "Every action recorded and checkable.", { architecture: ["hash-chained events"] }, "verification", "External anchoring of the chain.", ["lt-history", "agent-audit"], NA),
  ] },
  { id: "integrations", name: "Connectors, APIs and services", entries: [
    E("connectors", "Connectors to the person's services", "Gmail, Calendar, Drive, Slack, Notion, GitHub, CRMs.", { architecture: ["OAuth broker", "per-connector scopes", "audit"], permissions: ["each connector individually authorised in writing"] }, "authorisation", "Design the OAuth broker; build read-only connectors first.", ["prod-calendar-email"], APPROVAL),
    E("external-apis", "External APIs and services", "Call documented third-party APIs on request.", { tools: ["api.call (to build)"], permissions: ["per-API authorisation and allow-list"] }, "authorisation", "Allow-listed read-only API calls first.", [], APPROVAL),
    E("tool-servers", "Open tool protocols (MCP-style servers)", "Plug in tool servers without custom code.", { architecture: ["tool registry adapter", "permission mapping"] }, "design", "Map a tool-server description onto the tool registry with the same gates.", [], APPROVAL),
    E("webhooks-events", "Webhooks and event triggers", "Start work when something happens elsewhere.", { architecture: ["signed webhook receiver", "objective triggers"] }, "design", "Signed receiver that creates objectives.", [], APPROVAL),
    E("devices-iot", "Devices and IoT", "Read sensors, control devices where authorised.", { providers: ["device APIs"], permissions: ["per-device authorisation"] }, "authorisation", "Long-horizon target.", [], APPROVAL),
  ] },
  { id: "quality", name: "Verification, quality and safety", entries: [
    E("quality-verification", "Verification of results", "Check outputs against sources, tests or exact computation.", { architecture: ["verifiers", "reality layer", "citation checks"] }, "verification", "Wire verification into more answer paths.", ["rel-verify", "r-guard", "citation"], NA),
    E("quality-source-authority", "Source authority and lock", "Rank sources; restrict critical domains to official ones.", { architecture: ["reality layer"] }, "verification", "Apply the lock to the chat (owner decision).", ["r-authority", "r-lock"], NA),
    E("quality-evaluation", "Continuous evaluation on unseen tasks", "Measure generalisation, not memorised benchmarks.", { architecture: ["hidden task sets", "regression tracking"] }, "design", "Build a rolling set of new real objectives with human-checked results.", ["rel-eval"], NA),
    E("quality-safety", "Safety and honest limits", "Refuses harm, states limits, never fabricates.", { architecture: ["gates", "sanitising", "prompt-leak guard"] }, "verification", "Red-team tests for the agent path.", ["rel-safety"], NA),
    E("quality-health", "Health and degradation reporting", "Knows which providers are up, says when degraded.", { architecture: ["health store"] }, "none", "Alerting when a provider stays degraded.", ["rel-health"], NA),
  ] },
  { id: "platform", name: "Platform and experience", entries: [
    E("platform-accounts", "Accounts, sync and privacy controls", "Sign-in, cross-device sync, export, delete.", { architecture: ["accounts", "D1"] }, "verification", "Two-factor and session management.", [], NA),
    E("platform-app", "Phone and desktop app", "Installable, fast, offline-tolerant.", { runtimes: ["PWA"] }, "verification", "Polish the PWA (decided: not an app store app).", [], NA),
    E("platform-enterprise", "Team and enterprise controls", "Roles, SSO, audit export, data retention.", { architecture: ["roles", "SSO", "retention"] }, "design", "After shared workspaces.", [], NA),
    E("platform-api", "Programmatic access (API)", "Let other software use Noria.", { architecture: ["API keys", "rate limits", "metering"] }, "design", "After the tool layer stabilises.", [], NA),
  ] },
];

// The capability list the owner named, kept as a checklist so none of it is dropped: each phrase must be covered by at least one entry (tested).
export const OWNER_LIST = ["reasoning", "web research", "deep research", "fact verification", "long-context", "pdf", "file analysis", "spreadsheet", "visualisation", "coding", "code execution", "debugging", "repository", "browsing", "web interaction", "forms", "computer", "image understanding", "image generation", "image editing", "audio", "video", "ocr", "mathematical", "scientific", "tutoring", "translation", "writing", "business analysis", "financial", "research report", "presentation", "structured document", "creative", "content generation", "productivity", "email", "calendar", "contacts", "cloud", "maps", "travel", "shopping", "real-time", "external api", "agentic", "multi-step", "long-running", "background", "scheduled", "persistent", "project memory", "artifact", "collaboration", "notification", "monitoring", "automation", "connector", "real-world action", "verification", "recovery", "approval"];

const RANK_I = ["none", "architecture", "foundation", "partial", "yes"], RANK_V = ["none", "component", "read_only", "real_runtime"];
// Builds the map with implemented/verified DERIVED from the registry (families), and connection from the tool registry (tools: [{name, available}]).
export function buildMap(families, tools = []) {
  const byId = new Map(); for (const f of families) for (const c of f.capabilities) byId.set(c.id, c);
  const live = new Set(tools.filter((t) => ["live", "connected", "degraded"].includes(t.available)).map((t) => t.name));
  const groups = GROUPS.map((g) => ({ id: g.id, name: g.name, entries: g.entries.map((e) => {
    const rows = e.families.map((id) => byId.get(id)).filter(Boolean);
    const assessed = rows.length > 0;
    const implemented = assessed ? rows.reduce((a, r) => (RANK_I.indexOf(r.implemented) > RANK_I.indexOf(a) ? r.implemented : a), "none") : "unassessed";
    const verified = assessed ? rows.reduce((a, r) => (RANK_V.indexOf(r.verified) > RANK_V.indexOf(a) ? r.verified : a), "none") : "unassessed";
    const toolNames = e.needs.tools.map((x) => x.replace(/\s*\(.*$/, "")), connected = toolNames.some((n) => live.has(n));
    const available = ["partial", "yes"].includes(implemented);
    const blocker = e.blocker;
    const parts = ["Target", implemented === "unassessed" ? "not yet assessed" : implemented === "none" ? "not yet implemented" : "implemented: " + implemented, verified === "unassessed" ? "" : verified === "none" ? "not yet verified" : "verified: " + verified.replace("_", " ")].filter(Boolean);
    if (BLOCKERS[blocker]) parts.push(BLOCKERS[blocker]);
    return { ...e, implemented, verified, available, connected, assessed, label: parts.join(" · ") };
  }) }));
  const all = groups.flatMap((g) => g.entries), count = (fn) => all.filter(fn).length;
  return { groups, summary: { entries: all.length, groups: groups.length, target: all.length, assessed: count((e) => e.assessed), unassessed: count((e) => !e.assessed), implemented_partial_or_yes: count((e) => ["partial", "yes"].includes(e.implemented)), verified_read_only_or_better: count((e) => ["read_only", "real_runtime"].includes(e.verified)), connected: count((e) => e.connected),
    by_blocker: Object.fromEntries(Object.keys(BLOCKERS).map((k) => [k, count((e) => e.blocker === k)])) },
    legend: { target: "Noria is meant to be able to do this. Every entry is a target; nothing here limits Noria.", implemented: "what has been built (from the capability registry)", verified: "what has been tested for real (from the registry)", available: "usable by a person today", connected: "a live tool or provider is wired to it", authorisation: "whether Noria is permitted to perform it", blocked_by: BLOCKERS,
      rule: "A missing provider, an unbuilt subsystem or a missing authorisation is an engineering gap to close. It is never evidence that the category of work is out of Noria's reach." } };
}
