// NORIA CAPABILITY FAMILIES — Target, Implemented, Verified.
//
// Noria and Noria Pro are meant to be general-purpose: able to take almost any legitimate objective, plan it, use tools, produce work,
// verify it, recover, and continue over time. The tests are instruments that measure the machine; they are NOT the definition of it.
// So every capability carries three separate facts:
//
//   target       what Noria is meant to be able to do (always true here: this list is the ambition, not a claim)
//   implemented  what has actually been built:     none | architecture | foundation | partial | yes
//   verified     what has been tested for real:    none | component | read_only | real_runtime
//
//   architecture  designed only            foundation  the mechanism exists but the capability is not usable yet
//   partial       usable with clear limits  yes          built and usable as described
//   component     a part is tested in isolation (offline or by script)
//   read_only     exercised in the real runtime, reading only, with a side-effect audit
//   real_runtime  exercised end to end in the real environment
//
// `via` names what it rests on: registry tools ("tool:web.search"), server routes ("route:/brain/research") or app modules ("app:dataeng.js").
// `evidence` names what verifies it: test files in noria-eval/, "live: ..." (a recorded real run) or "manual: ..." (by hand, not repeatable).
// `gap` says plainly what is missing. Rules that keep this honest are enforced by families_t.mjs against the tool registry.

export const IMPLEMENTED = ["none", "architecture", "foundation", "partial", "yes"];
export const VERIFIED = ["none", "component", "read_only", "real_runtime"];

const C = (id, name, implemented, verified, via, evidence, gap) => ({ id, name, target: true, implemented, verified, via: via || [], evidence: evidence || [], gap: gap || "" });

export const FAMILIES = [
  { id: "intelligence", name: "Intelligence and reasoning", capabilities: [
    C("reasoning", "Complex reasoning and multi-step problem solving", "partial", "component", ["route:/brain/ask"], ["bench.mjs", "audit.mjs"], "No general chain-of-thought verifier; logic questions get a form check."),
    C("decompose", "Planning and task decomposition", "foundation", "component", ["route:/brain/plan"], ["planner_t.mjs", "live: models planned five unseen objectives, validated against the registry"], "Read-only planner; plans can now be saved and revised as task graphs, but there is no screen for it."),
    C("uncertainty", "Uncertainty and hallucination management", "partial", "component", ["route:/brain/ask"], ["bench.mjs", "office_evidence_t.mjs", "temporal_t.mjs"], "No calibrated confidence; relies on refusals and fact checks."),
    C("contradiction", "Contradiction detection across sources", "architecture", "none", [], [], "Not built."),
    C("decision", "Decision support and hypothesis generation", "partial", "none", ["route:/brain/ask"], [], "Model answers only; not evaluated."),
  ] },
  { id: "research", name: "Research", capabilities: [
    C("web-research", "Live web research and current information", "yes", "real_runtime", ["tool:web.search"], ["feeds_t.mjs", "worker_int_t.mjs", "search_layer_t.mjs"], "The open-web provider is out of allowance (HTTP 432): coverage is degraded to Wikipedia and news feeds."),
    C("web-page-read", "Reading one web page in full, safely, with provenance (not just a search snippet)", "partial", "read_only", ["tool:web.read", "app:agent/web-read.js"], ["web_read_t.mjs (69 checks offline against a fully injected fake network and DNS: obfuscated-IP and DNS-rebinding SSRF protection on every redirect hop, content-type/size/timeout limits, real HTML-to-text extraction, the structural test that a page whose text merely contains fields named tool/approved/plan/grants creates no tool call, approval or plan step, and that every refusal carries an honest 4xx status)", "live: verify-web-read on noria.africa, 2026-09-22, no sign-in needed: 11 of 11 against the real internet — a genuine public page fetched and extracted with provenance; a literal loopback address, the cloud metadata address, an obfuscated hex address and the hostname \"localhost\" all refused before any fetch; a real public domain (localtest.me, which by design resolves to 127.0.0.1) refused by the real Cloudflare DNS-over-HTTPS resolver, not just by name; a disallowed scheme refused; a real 404 from a real server reported by status, not swallowed; the live response shape carries no field an automated caller could read as an instruction"], "SSRF protection resolves the address itself (DNS-over-HTTPS) and re-validates every redirect hop, catching literal IPs in obfuscated forms and public hostnames that resolve to a private address; this is now proven against the real internet, not only an injected fake network. One real production bug was found and fixed in this pass: refusals were falling through to a default HTTP 502, and Cloudflare's edge silently replaces any 502/503/504 body with its own generic error page — the caller never saw the real reason. Every web.read error now carries an explicit 4xx status. Still not measured: a live redirect chain against a real host (the redirect logic itself is proven offline only), real body-size streaming truncation against a genuinely oversized live response, and any rebinding domain other than localtest.me. No screen yet for a person to read a page directly."),
    C("deep-research", "Deep research reports with citations (Noria Pro)", "yes", "real_runtime", ["tool:research.deep"], ["manual: research_live.py, one real Pro brief"], "A few briefs a day; depends on the open web; not automated."),
    C("temporal", "Temporal reasoning (latest, next, last year)", "yes", "component", ["route:/brain/ask"], ["temporal_t.mjs", "office_evidence_t.mjs"], ""),
    C("citation", "Source citation and verification", "partial", "component", ["route:/brain/ask", "app:rag.js"], ["rag_t.mjs", "verify_t.mjs"], "Citation checks exist in the RAG module, which is not connected."),
    C("academic", "Academic literature research", "none", "none", [], [], "No academic sources connected."),
    C("longitudinal", "Monitoring a topic over time", "none", "none", [], [], "Needs background execution."),
  ] },
  { id: "conversation", name: "Conversation understanding and memory", capabilities: [
    C("conv-state", "Real conversation state: an active objective, entities produced, decisions, corrections, tracked across turns instead of a blind recency window", "partial", "real_runtime", ["app:public/conversation-state.js", "app:public/workspace.js", "app:public/brain.js"], ["conversation_state_t.mjs (23 checks: the exact 'Build the authentication system → Use Clerk → Make it production ready → the login is broken → Fix it → Is it done?' scenario from the architecture spec, a real new-topic vs continuation boundary, entity tracking from produced code, corrections, defensive repair of a malformed stored state)", "live: noria.africa, 2026-09-22, real production chat, no scripting: 'I'm starting a side project called Nimbus... backend language must be Go.' followed by five genuinely unrelated questions (arithmetic, geography, chemistry) — twelve messages later, 'What language did I say to use for it?' was answered correctly ('Go'). Under the OLD behaviour (a blind last-8-messages window, both client and server) that founding message could not have reached the model at all; the five filler exchanges never mentioned Go"], "This is real, mechanical tracking (message-derived signals: is this a continuation or a new topic, was code/an image produced, does this look like a correction) — not a natural-language-understanding engine, and it does not claim to be one. State lives client-side, inside the same conversation object that already syncs to the account as a payload opaque to the server (noria-ai/schema.sql): no new server table, no change to what the server can read. STILL MISSING, honestly: genuine entity/reference resolution beyond the heuristic trigger-word list (no clarification is asked when a reference is genuinely ambiguous); long-term memory (memory.js) is untouched by this work and still has no provenance, versioning or per-fact correction; the Reality Layer is still not connected to chat; chat and the agentic task-graph system still do not share state; and state re-indexing after a very long conversation is truncated for sync is a disclosed, not-yet-handled gap (account.js pack()). One real bug was found and fixed by this same live test: the code-block-language extraction that feeds entity tracking was counting a fence's CLOSING marker as a second block, doubling the count (fixed; regression-tested in workspace_answer_text_t.mjs)."),
  ] },
  { id: "agentic", name: "Agentic execution", capabilities: [
    C("agent-plan", "Autonomous task planning", "foundation", "component", ["route:/brain/plan"], ["planner_t.mjs"], "Plans one objective at a time."),
    C("agent-exec-seq", "Sequential and parallel execution of a plan", "foundation", "read_only", ["tool:web.search", "tool:calc.math"], ["executor_t.mjs", "executor_live_t.mjs", "live: real browser runs, side-effect audit clean"], "Read-only tools only; not connected to the app screen."),
    C("agent-recovery", "Retries, alternatives, recovery, cancellation", "foundation", "component", ["app:agent/executor.js"], ["executor_t.mjs"], "Only three alternatives are declared."),
    C("agent-approval", "Human approval gates", "foundation", "component", ["app:agent/executor.js", "app:agent/gate.js"], ["executor_t.mjs", "executor_live_t.mjs"], "No acting tool exists to gate yet."),
    C("agent-audit", "Tamper-evident audit trail", "foundation", "component", ["app:agent/audit.js"], ["executor_t.mjs"], "Persisted into the project history when run through the graph runner; the executor alone still holds it in memory."),
    C("browser-op", "Operating a browser or websites", "none", "none", ["tool:browser.navigate"], [], "Not built."),
    C("automation", "Workflow automation", "none", "none", [], [], "Not built."),
    C("background", "Background, scheduled and long-running tasks", "none", "none", [], [], "Persistent task state and a paused/resumed path exist; nothing runs without the screen open, and the background path is switched off."),
  ] },
  { id: "documents", name: "Documents", capabilities: [
    C("doc-read", "Reading PDF, Word, text, CSV and Excel files", "yes", "component", ["tool:doc.read", "tool:data.query"], ["docread_t.mjs", "data/test-data.mjs"], "Long-document retrieval is keyword-based; the RAG pipeline is not connected."),
    C("doc-ocr", "Scanned documents and photo text (OCR)", "partial", "none", ["app:workspace.js"], [], "On-device photo text only; scanned PDFs not supported."),
    C("doc-generate", "Generating and exporting Word, Excel, PowerPoint and PDF", "yes", "none", ["tool:doc.export"], ["manual: browser"], "Libraries load from a CDN; no automated test."),
    C("doc-multi", "Analysing many documents together", "none", "none", ["tool:knowledge.search"], [], "Needs a knowledge store."),
    C("doc-forms", "Contracts, invoices and forms as structured data", "partial", "none", ["route:/brain/ask"], [], "Model reading only."),
  ] },
  { id: "coding", name: "Coding and software engineering", capabilities: [
    C("code-write", "Writing code", "yes", "component", ["route:/brain/ask"], ["bench.mjs"], "Written, not run."),
    C("code-debug", "Debugging and refactoring", "partial", "none", ["route:/brain/ask"], [], "Depends on code execution, which is not built yet (the sandbox is in progress): code is written as text and not yet run or tested."),
    C("code-run", "Running code in isolated runtimes: one capability (code.run), many possible runtimes", "foundation", "read_only", ["tool:code.run", "app:agent/code-exec.js", "app:sandbox.js"], ["code_exec_t.mjs", "sandbox_core_t.mjs", "live: verify-code on noria.africa, 2026-09-22, real browser sandbox + production store + signed-in session: 22 of 22 (sales analysis with a malformed row and independent cross-check, table + report + SVG chart artifacts; failing tests -> revision -> pass; wrong loan figure refused by the independent check; hostile output neutralised; 0 unexpected requests; history chain unbroken)", "live: verify-python on noria.africa, 2026-09-22: a Python computation and a JavaScript computation verified each other through the same code.run tool with neither request naming a runtime, and the result named which runtime the policy chose — direct production evidence that the capability is runtime-agnostic"], "The abstraction, the authority levels and the execution policy are built and verified in production, now proven across two runtimes (browser JavaScript and browser Python) with neither the planner nor the caller naming which one ran. A third and fourth runtime (server-isolated) remain not built. Per-runtime and per-use status is in the rows below."),
    C("code-exec-js", "Sandboxed JavaScript execution", "partial", "read_only", ["tool:code.run", "app:sandbox.js"], ["sandbox_core_t.mjs", "code_exec_t.mjs", "manual: escape battery (verify-sandbox page), 56 of 56 in Chrome 152 against a local server: network, page, storage, files, worker/iframe escape, limit bypass, memory, output smuggling; the server log shows zero requests from sandboxed code", "live: verify-sandbox on noria.africa, 2026-09-22, Firefox 156 (a different engine from the Chrome used locally): 56 of 56 on the production origin, after a first run of 55 of 56 whose one miss was the check expecting Chrome's error name for runaway recursion"], "Usable as the code.run tool with no per-run approval inside the sealed boundary; isolation verified on the production origin in Firefox and locally in Chrome. Limits: memory cannot be capped inside a browser page (only the timeout bounds an unbounded gradual allocation); no screen yet for a person to run code directly;"),
    C("code-exec-py", "Sandboxed Python execution", "partial", "read_only", ["tool:code.run", "app:sandbox-python-core.js"], ["manual: escape battery (verify-python page), 38 of 38 in Chrome against a local server: standard library only, no packages, no network, no files, no processes, no page/session access, five independent timeout-bypass attempts, memory refusals, cross-run isolation, structural output-as-data rule, cross-language verification", "live: verify-python on noria.africa, 2026-09-22, Firefox 156 (a second, different engine from the Chrome used locally): 38 of 38 on the production origin, after a first production run of 37 of 38 whose one miss was a gap in the test itself (the service-worker attack read a property but never attempted to register one) — fixed to actually attempt registration and re-verified clean", "live: verify-code on noria.africa, 2026-09-22: a Python code.run step ran inside a real stored task-graph objective (not just the isolation battery), its output verified by an independent JavaScript computation in a second sandbox"], "The official pyodide npm package (314.0.7, MPL-2.0), downloaded once, hashed against the registry's published integrity value, hosted on this site, and hash-checked again by the sandbox before every load; its installable-package list is stripped to empty so nothing beyond the standard library can be named. Isolation is verified, and it has now run as a real task-graph objective in production (data analysis — see code-data-analysis); the test-fix loop (see code-testing) has not yet used Python. Same browser-only limit as JavaScript: memory cannot be capped, only the timeout bounds it. No numeric/scientific packages (none can be loaded)."),
    C("code-data-analysis", "Data analysis through sandbox execution (CSV in, verified tables, reports and charts out)", "foundation", "read_only", ["tool:code.run", "tool:artifact.write"], ["code_e2e_t.mjs", "manual: verify-code page in a real browser against a local store, 21 of 21 (analysis with a malformed row, independent cross-check, table + report + SVG chart artifacts, results fed back into the task graph)", "live: verify-code on noria.africa, 2026-09-22, real browser sandbox + production store + signed-in session: 22 of 22 (sales analysis with a malformed row and independent cross-check, table + report + SVG chart artifacts; failing tests -> revision -> pass; wrong loan figure refused by the independent check; hostile output neutralised; 0 unexpected requests; history chain unbroken)", "manual: verify-code page in a real browser against a local store, 30 of 30, adding the SAME analysis run in Python and cross-checked by an independent JavaScript computation", "live: verify-code on noria.africa, 2026-09-22: 30 of 30, including the Python objective (same numbers as the plain host code on the same untidy file; table, report and SVG chart written through emit_artifact(); project memory set from the Python result)"], "Verified in production with code written by the check and a real signed-in session (about 3 minutes end to end for both languages: each graph step is slow on the production network). Not usable by a person yet without a plan; not measured with model-written code. Now verified for BOTH JavaScript and Python, with cross-language verification demonstrated directly in production (a Python computation checked by an independent JavaScript one, in a second sandbox, through the same task)."),
    C("code-testing", "Code testing and debugging loops (run tests, read failures, fix, rerun)", "foundation", "read_only", ["tool:code.run"], ["code_e2e_t.mjs", "manual: verify-code page in a real browser against a local store: failing tests fail the step, the plan is revised with the real failures, the fixed code passes", "live: verify-code on noria.africa, 2026-09-22, real browser sandbox + production store + signed-in session: 22 of 22 (sales analysis with a malformed row and independent cross-check, table + report + SVG chart artifacts; failing tests -> revision -> pass; wrong loan figure refused by the independent check; hostile output neutralised; 0 unexpected requests; history chain unbroken)"], "The loop (failing tests fail the step, the plan is revised with the real failures, the fixed code passes) is verified in production with scripted fixes, in JAVASCRIPT ONLY — Python is a verified sandbox runtime (see code-exec-py) but has not been run through this test-and-fix loop as a task-graph objective. Fixes written by a real model are not measured."),
    C("code-model-loop", "The real model-to-code loop: a user objective, real reasoning/planning, MODEL-GENERATED code (not developer-authored test code), code.run, independent verification, result assessment, a live revision when necessary, rerun, a verified artifact, task-graph persistence, memory/project update", "foundation", "component", ["tool:code.run", "route:/brain/plan", "route:/brain/replan", "app:agent/control.js"], ["live: verify-model-loop on noria.africa, 2026-09-22 (prior design, since superseded — see below): a seeded, disclosed starting bug (an unsorted-input median) genuinely failed and was correctly classified as a REPLAN, not a blind retry; the live model's first proposed fix was correct (it sorts before taking the median); a second, real proposal on the same objective was correctly REFUSED by the graph's own validation for naming an already-used task key, proving the safety net rejects a bad live proposal rather than corrupting the graph; a separate fresh, unscripted objective had its own invalid proposal refused for introducing a dependency cycle, and reported an honest 'partial' state with the wrong numeric result disclosed rather than a false 'completed' claim"], "The 2026-09-22 evidence above is real but was measured against a narrower design (one objective used a seeded starting bug rather than fully model-generated code). The check has since been substantially rebuilt to the owner's precise specification: four objectives, none seeded — (1) a straightforward data-analysis objective planned AND coded entirely live, checked for correctness, an independent cross-check if the model added one, an actual artifact/memory update, and that the plan names code.run only, never a runtime directly; (2) the model's OWN first code may contain a real bug, reported honestly either way, with revision-not-retry checked when it does; (3) the model's own code may produce a plausible but WRONG result, with a disclosed, hardcoded independent cross-check (the one part not model-written) attached to decide, not mere execution; (4) the model's own code may need something outside the sealed sandbox, checked for safe refusal via both the graph's own classification and a live confirmation that nothing reached the real network. This redesigned check has not yet been run in production — it needs the owner's signed-in session and Pro code, same as before. The open design question already found (a refused revision proposal does not currently get a further attempt within the same run's revision budget) still applies and is unchanged by this rebuild."),
    C("code-server-isolated", "Server-side isolated execution (memory, CPU and time enforced)", "none", "none", [], [], "Infrastructure required: an isolated execution service with enforced limits, behind the same code.run capability and chosen by the execution policy."),
    C("code-repo", "Repositories and deployment workflows", "none", "none", [], [], "Not built."),
    C("code-security", "Security analysis", "none", "none", [], [], "Not built."),
  ] },
  { id: "data", name: "Data intelligence", capabilities: [
    C("data-tables", "Exact spreadsheet and CSV analysis", "yes", "component", ["tool:data.query"], ["data/test-data.mjs (1,200 rows against pandas)"], "Runs on the device; very large files untested."),
    C("data-stats", "Statistics and modelling", "partial", "none", ["tool:data.query"], [], "Counts, means, medians, correlation only."),
    C("data-viz", "Charts and tables", "yes", "none", ["tool:chart.draw"], ["manual: browser"], "Chart library loads from a CDN; no automated test."),
    C("data-sql", "SQL and databases", "none", "none", ["tool:sql.query"], [], "Not built."),
    C("data-forecast", "Forecasting, anomaly detection, dashboards", "none", "none", [], [], "Not built."),
  ] },
  { id: "creation", name: "Creation", capabilities: [
    C("create-text", "Writing, translation and educational material", "yes", "component", ["route:/brain/ask"], ["bench.mjs"], "Quality is not measured beyond the benchmark's language checks."),
    C("create-image", "Image creation", "partial", "none", ["tool:image.generate"], [], "Depends on a small daily allowance; often unavailable."),
    C("create-slides", "Presentations", "yes", "none", ["tool:doc.export"], ["manual: browser"], "See exports."),
    C("create-web", "Websites and applications", "partial", "none", ["route:/brain/ask"], [], "Produces code as text. Building, running and deploying it need the code-execution sandbox (in progress) and a preview runtime."),
    C("create-av", "Audio and video workflows", "none", "none", [], [], "Not built."),
  ] },
  { id: "multimodal", name: "Multimodal", capabilities: [
    C("vision", "Understanding photos and images (Noria Pro)", "partial", "none", ["tool:vision.describe"], [], "Depends on the same daily allowance; untested by script."),
    C("speech", "Speech in and out (Noria Pro)", "partial", "none", ["tool:speech.speak"], [], "Depends on the daily allowance; untested by script."),
    C("video", "Video understanding", "none", "none", [], [], "Not built."),
    C("visual-reasoning", "Charts, diagrams and screenshots", "none", "none", [], [], "Not built."),
  ] },
  { id: "business", name: "Business", capabilities: [
    C("biz-research", "Market and competitor research", "partial", "none", ["tool:web.search", "tool:research.deep"], [], "Rests on web research, which is degraded."),
    C("biz-docs", "Plans, proposals and structured business documents", "yes", "none", ["route:/brain/ask"], [], "Guided document flows; not measured."),
    C("biz-finance", "Financial analysis and modelling", "partial", "none", ["tool:data.query"], [], "Basic figures only."),
    C("biz-ops", "Operations, sales, procurement and customer workflows", "none", "none", [], [], "Needs connectors and automation."),
  ] },
  { id: "productivity", name: "Personal productivity", capabilities: [
    C("prod-memory", "Remembering what you share (on your device)", "yes", "component", ["tool:memory.device"], ["memory_t.mjs"], "Facts only; no projects or tasks."),
    C("prod-travel", "Travel and visa preparation guidance", "partial", "none", ["route:/brain/ask"], [], "Guidance from general knowledge and web research."),
    C("prod-calendar-email", "Email, calendar and reminders", "none", "none", ["tool:email.send", "tool:calendar.create"], [], "Not built; needs your own account connections and approval gates."),
    C("prod-projects", "Notes, tasks and projects", "none", "none", [], [], "Not built."),
  ] },
  { id: "long-term", name: "Long-term intelligence", capabilities: [
    C("lt-project", "Projects with objectives, tasks and progress", "partial", "read_only", ["route:/graph/op", "app:agent/graph-store.js"], ["graph_t.mjs", "graph_api_t.mjs", "live: owner check page on noria.africa, 2026-09-21, 16/16 with the owner's real session, side-effect audit clean (0 unexpected)"], "Projects, objectives and tasks are saved per account in production and were exercised with a real session. Never used by a second real account; no screen yet, only the API and the owner check page."),
    C("lt-graph", "Persistent task graphs with a state machine", "partial", "read_only", ["app:agent/graph.js", "app:agent/graph-store.js"], ["graph_t.mjs", "live: owner check page on noria.africa, 2026-09-21, 16/16 with the owner's real session, side-effect audit clean (0 unexpected)"], "A real plan, a revision and a replacement ran through the deployed store and the real read-only calculator route, with a clean side-effect audit. Reachable only through the API and the owner check page: there is no app screen yet."),
    C("lt-dataflow", "Data flowing from one step to the next", "partial", "read_only", ["app:agent/graph.js"], ["graph_t.mjs", "calc_t.mjs", "live: owner check page on noria.africa, 2026-09-21, 16/16 with the owner's real session, side-effect audit clean (0 unexpected)"], "Values flowed between tasks, from memory and from artifacts in the live run (read-only tools only). Reachable only through the API and the owner check page: there is no app screen yet."),
    C("lt-resume", "Resuming after an interruption without repeating work", "partial", "read_only", ["app:agent/graph-runner.js", "app:agent/graph-store.js"], ["graph_t.mjs", "graph_api_t.mjs", "live: owner check page on noria.africa, 2026-09-21, 16/16 with the owner's real session, side-effect audit clean (0 unexpected)"], "Paused at a budget, resumed by a fresh client, no finished work repeated (live). Reachable only through the API and the owner check page: there is no app screen yet. A real crash mid-task was not tested in production."),
    C("lt-artifacts", "Versioned artifacts produced by steps and passed between them", "partial", "read_only", ["app:agent/graph-store.js", "tool:artifact.write", "tool:artifact.read"], ["graph_t.mjs", "control_t.mjs", "live: owner check page on noria.africa, 2026-09-21, 16/16 with the owner's real session, side-effect audit clean (0 unexpected)"], "Text artifacts written, versioned and read back by later steps in production; old versions kept. Text and JSON up to 200 KB only; no binary files, no export. Reachable only through the API and the owner check page: there is no app screen yet."),
    C("lt-memory", "Project memory and decisions (viewable, correctable, deletable)", "partial", "read_only", ["app:agent/graph-store.js"], ["graph_t.mjs", "graph_api_t.mjs", "live: owner check page on noria.africa, 2026-09-21, 16/16 with the owner's real session, side-effect audit clean (0 unexpected)"], "Project memory feeding later tasks was exercised live; correcting and deleting memory from a screen does not exist yet. Reachable only through the API and the owner check page: there is no app screen yet."),
    C("lt-history", "A persistent, tamper-evident history linked to tasks and attempts", "partial", "read_only", ["app:agent/graph-store.js"], ["graph_t.mjs", "live: owner check page on noria.africa, 2026-09-21, 16/16 with the owner's real session, side-effect audit clean (0 unexpected)"], "An 88-event history verified as one unbroken chain in production. It detects changes and removals of past events; it does not stop a database operator from rewriting the whole chain."),
    C("lt-continue", "Continuing an objective as new information arrives", "partial", "read_only", ["app:agent/control.js", "app:agent/graph-store.js"], ["control_t.mjs", "live: owner check page on noria.africa, 2026-09-21, 16/16 with the owner's real session, side-effect audit clean (0 unexpected)"], "New information was recorded and the stale work was found and replaced live; old outputs and artifact versions kept. Acting steps are never repeated automatically. Reachable only through the API and the owner check page: there is no app screen yet."),
    C("lt-retry-replan", "Telling a retry from a genuine change of plan", "foundation", "read_only", ["app:agent/control.js"], ["control_t.mjs", "live: owner check page on noria.africa, 2026-09-21, 16/16 with the owner's real session, side-effect audit clean (0 unexpected)"], "The replan side ran live (bad input replanned at once, no retries). The bounded-retry side is tested offline only. Real-model proposals are unmeasured."),
    C("lt-auto-revise", "Revising the task graph automatically after a failure", "foundation", "read_only", ["app:agent/control.js", "route:/brain/replan"], ["control_t.mjs", "worker_int_t.mjs", "live: owner check page on noria.africa, 2026-09-21, 16/16 with the owner's real session, side-effect audit clean (0 unexpected)"], "The revision machinery ran live after a real failure (scripted proposer, so it proves the mechanics, not the model). Real-model revision is unmeasured until a Pro code is used on the owner check page. Route is Pro-gated."),
    C("lt-preserve", "Keeping finished work and artifacts when a plan changes", "partial", "read_only", ["app:agent/graph-store.js"], ["control_t.mjs", "graph_t.mjs", "live: owner check page on noria.africa, 2026-09-21, 16/16 with the owner's real session, side-effect audit clean (0 unexpected)"], "A revision kept finished work and its history live; the failed task stayed visible. Reachable only through the API and the owner check page: there is no app screen yet."),
    C("lt-verify-feedback", "Verification results feeding back into planning", "foundation", "component", ["app:agent/graph-runner.js", "app:agent/control.js"], ["control_t.mjs"], "The re-planner receives what verification said; whether a real model uses it well is not measured."),
    C("lt-pause-resume", "Pausing and resuming long objectives", "partial", "read_only", ["app:agent/graph-store.js", "app:agent/graph-runner.js"], ["control_t.mjs", "graph_api_t.mjs", "live: owner check page on noria.africa, 2026-09-21, 16/16 with the owner's real session, side-effect audit clean (0 unexpected)"], "Verified live: budget pause with a checkpoint, then resume by a fresh client. Reachable only through the API and the owner check page: there is no app screen yet. Pausing by hand is tested offline only."),
    C("lt-screen", "A project screen: task graphs, approvals, artifacts, memory, failures, revisions, resumptions", "foundation", "component", ["app:projects.js"], ["manual: opened in a real browser against a local worker with seeded data, 2026-09-21; not yet seen in production"], "Observation only: it does not yet run, approve, pause, resume or edit anything. Not yet checked against production data."),
    C("lt-background", "Continuing objectives without the screen open", "architecture", "none", [], [], "The path (agent/background.js, tested in control_t.mjs) is written and tested but shipped switched off; no scheduled job calls it and it needs the owner's authorisation."),
    C("lt-knowledge", "Knowledge bases with hybrid retrieval", "foundation", "component", ["tool:knowledge.search", "app:rag.js", "app:noria-ai/kb.js"], ["rag_t.mjs", "kb_t.mjs", "kb_tool_t.mjs"], "Storage, hybrid search (keywords plus Workers AI embeddings), citation checks and the tool path are built and tested offline and on a local worker. Not yet deployed or checked in production; how well the real embedding model finds meaning is unmeasured; the tool is registered as not built until a production check passes; not connected to the chat pipeline."),
  ] },
  { id: "reliability", name: "Reliability and control", capabilities: [
    C("rel-verify", "Verifying answers against sources before showing them", "yes", "real_runtime", ["route:/brain/ask"], ["bench.mjs", "audit.mjs", "live-check.mjs"], "Weaker while web search is degraded."),
    C("rel-health", "Honest health and capability reporting", "yes", "real_runtime", ["route:/brain/capabilities", "route:/brain/tools"], ["search_layer_t.mjs", "worker_int_t.mjs", "tools_state_t.mjs"], ""),
    C("rel-safety", "Permissions and a read-only gate that no runtime can bypass", "yes", "real_runtime", ["tool:web.search"], ["executor_live_t.mjs", "feeds_t.mjs"], "Only read-only execution is authorised."),
    C("rel-eval", "Evaluation on unseen tasks", "architecture", "none", [], [], "Designed (held-out generated tasks); the current benchmark is a regression check, not a measure of generality."),
  ] },
  { id: "reality", name: "Reality and verification", capabilities: [
    C("r-authority", "Source authority hierarchy (official, licensed, secondary, general web, user claims)", "partial", "component", ["app:agent/reality.js", "tool:web.search"], ["reality_t.mjs", "worker_int_t.mjs"], "Used by the agent tools (web.search marks each source's authority). The chat answers do not use it yet: that path is unchanged by rule."),
    C("r-passport", "A data passport on every fact: source, authority, time published, time retrieved, validity, expiry", "partial", "read_only", ["app:agent/reality.js", "tool:fx.rate", "tool:crypto.price", "tool:weather.get"], ["reality_t.mjs", "reality_feeds_t.mjs", "live: feeds_t.mjs against noria.africa, 2026-09-21: VERIFIED Accra 24.4 C (MET Norway + Open-Meteo), USD/GHS 11.46 (two feeds), Bitcoin (Coinbase, Kraken, CoinGecko); evidence graph returned"], "Attached to fx, crypto and weather answers. Other tools and the chat do not carry passports yet."),
    C("r-conflict", "Cross-checking and conflict resolution between sources", "partial", "component", ["app:agent/reality.js", "tool:fx.rate", "tool:crypto.price", "tool:weather.get"], ["reality_t.mjs", "reality_feeds_t.mjs", "worker_int_t.mjs"], "Real for three domains (exchange rates, crypto, weather). Rules: authority outranks numbers, independent providers only, different bases are not compared."),
    C("r-freshness", "Freshness windows per kind of information", "partial", "component", ["app:agent/reality.js"], ["reality_t.mjs", "reality_feeds_t.mjs"], "Windows exist for twelve kinds of information; only the three connected domains use them today. Free exchange-rate feeds update once a day, so rates are labelled daily reference rates, not trading prices."),
    C("r-nostate", "An explicit no-answer state (verified / partially verified / conflicting / stale / unavailable / unverified / unknown)", "partial", "component", ["app:agent/reality.js", "tool:fx.rate", "tool:crypto.price", "tool:weather.get"], ["reality_t.mjs", "worker_int_t.mjs"], "The live-data tools fail with the plain statement instead of returning a number they cannot verify. The chat pipeline has its own separate refusals and is not yet driven by these statuses."),
    C("r-guard", "The model may not overrule the verdict (a drafted answer is checked against it)", "foundation", "component", ["app:agent/reality.js"], ["reality_t.mjs"], "Built and tested; not yet wired into any answer path."),
    C("r-entity", "Entity resolution (airports, organisations; ambiguity reported, never guessed)", "foundation", "component", ["app:agent/reality.js"], ["reality_t.mjs"], "About 25 airports and a handful of organisations: a seed table, not a global registry."),
    C("r-timemodel", "Entity + attribute + value + time (current is not historical)", "foundation", "component", ["app:agent/reality.js"], ["reality_t.mjs"], "Built as a library; no store of such facts is connected yet."),
    C("r-lock", "Source lock for critical domains (immigration, law, medicine, finance)", "partial", "component", ["app:agent/reality.js", "tool:web.search"], ["reality_t.mjs", "worker_int_t.mjs"], "web.search flags a locked question and marks which sources are admissible. The chat answers are not locked yet."),
    C("r-graph", "An evidence graph behind each verified answer", "partial", "read_only", ["app:agent/reality.js", "tool:fx.rate", "tool:crypto.price", "tool:weather.get"], ["reality_t.mjs", "reality_feeds_t.mjs", "live: feeds_t.mjs against noria.africa, 2026-09-21: VERIFIED Accra 24.4 C (MET Norway + Open-Meteo), USD/GHS 11.46 (two feeds), Bitcoin (Coinbase, Kraken, CoinGecko); evidence graph returned"], "Returned with each verified live-data answer; not displayed anywhere on a screen yet."),
    C("r-fx", "Exchange rates, cross-checked across independent feeds", "partial", "read_only", ["tool:fx.rate"], ["reality_feeds_t.mjs", "worker_int_t.mjs", "live: feeds_t.mjs against noria.africa, 2026-09-21: VERIFIED Accra 24.4 C (MET Norway + Open-Meteo), USD/GHS 11.46 (two feeds), Bitcoin (Coinbase, Kraken, CoinGecko); evidence graph returned"], "Daily reference rates from an ECB reference (where the currency is covered) and two aggregators; not real-time trading prices. Agreement was verified live; the conflict and stale paths were exercised offline only (a real disagreement cannot be forced in production)."),
    C("r-crypto", "Cryptocurrency prices, cross-checked across exchanges", "partial", "read_only", ["tool:crypto.price"], ["reality_feeds_t.mjs", "worker_int_t.mjs", "live: feeds_t.mjs against noria.africa, 2026-09-21: VERIFIED Accra 24.4 C (MET Norway + Open-Meteo), USD/GHS 11.46 (two feeds), Bitcoin (Coinbase, Kraken, CoinGecko); evidence graph returned"], "Four exchanges and an aggregator compared; a few major coins only. Agreement was verified live; the conflict and stale paths were exercised offline only (a real disagreement cannot be forced in production)."),
    C("r-weather", "Weather, cross-checked between an official service and a model", "partial", "read_only", ["tool:weather.get"], ["reality_feeds_t.mjs", "worker_int_t.mjs", "live: feeds_t.mjs against noria.africa, 2026-09-21: VERIFIED Accra 24.4 C (MET Norway + Open-Meteo), USD/GHS 11.46 (two feeds), Bitcoin (Coinbase, Kraken, CoinGecko); evidence graph returned"], "Current temperature only, from two providers. Agreement was verified live; the conflict and stale paths were exercised offline only (a real disagreement cannot be forced in production)."),
    C("r-router", "Deciding when a question needs outside verification, and choosing the sources", "foundation", "read_only", ["app:agent/reality-router.js", "route:/brain/reality/route"], ["reality_router_t.mjs", "worker_int_t.mjs", "live: route_live.mjs against noria.africa, 2026-09-21: 29 of 29 real phrasings routed as expected after five gaps found on the first run were fixed"], "Domain-general and tested on about thirty phrasings; says \"cannot verify\" for domains with no connected source. A rule-based first version; a model-assisted intent step is not built. Not connected to the chat. Verified only as a live routing diagnostic (pure computation): the chat does not call it."),
    C("r-chat", "The conversational interface using the same verification for current or factual questions", "architecture", "none", [], [], "Designed: request -> intent -> router -> tools -> reality layer -> verdict -> answer with evidence. Deliberately not connected: it needs its own tested rollout and the owner's decision."),
    C("r-domains", "The same verification across research, documents, business, government, legislation, immigration, company, finance, travel and science", "architecture", "none", [], [], "The router, freshness windows and source locks already name these domains; each needs a connected authoritative source before it can be verified. Only exchange rates, crypto, weather and computed date and arithmetic are connected."),
    C("r-flights", "Flight status from airline, airport and aviation data", "none", "none", [], [], "Infrastructure required: an aviation data provider and a flights adapter through the reality layer. Until then Noria states that it cannot verify flight status yet, and does not guess."),
    C("r-traffic", "Live traffic", "none", "none", [], [], "Infrastructure required: a routing/traffic provider (free routing services exist; live traffic usually needs a licence) and an adapter."),
    C("r-markets", "Stock and market prices from a licensed feed", "none", "none", [], [], "Infrastructure required: a market-data provider (delayed quotes are often free; real-time is licensed) and an adapter."),
    C("r-visa", "Visa, immigration and appointment systems from official sources", "none", "none", [], [], "Infrastructure required: official per-country sources and adapters. The source lock is ready."),
    C("r-law", "Law and regulation from official sources", "none", "none", [], [], "Infrastructure required: official legislation and court sources and adapters. The source lock is ready."),
    C("r-registry", "Company registrations and business registers", "none", "none", [], [], "Infrastructure required: a business-registry provider and an adapter."),
  ] },
];

// The rules that keep the three facts honest. tools: the registry as { name: { state } } (from listTools).
export function validateFamilies(families, toolStates, fileExists) {
  const problems = [], ids = new Set();
  const rank = (arr, v) => arr.indexOf(v);
  for (const f of families) for (const c of f.capabilities) {
    const at = f.id + "/" + c.id;
    if (ids.has(c.id)) problems.push(at + ": duplicate id"); ids.add(c.id);
    if (c.target !== true) problems.push(at + ": target must be true (the list is the ambition)");
    if (!IMPLEMENTED.includes(c.implemented)) problems.push(at + ": bad implemented level");
    if (!VERIFIED.includes(c.verified)) problems.push(at + ": bad verified level");
    if (c.verified !== "none" && ["none", "architecture"].includes(c.implemented)) problems.push(at + ": cannot be verified when only " + c.implemented);
    if (c.verified !== "none" && !c.evidence.length) problems.push(at + ": verified without evidence");
    if (c.verified === "none" && c.evidence.some((e) => !/^manual:/i.test(e))) problems.push(at + ": lists evidence but says not verified");
    if (["read_only", "real_runtime"].includes(c.verified) && !c.evidence.some((e) => /^live:|^manual:|feeds_t|executor_live_t|worker_int_t|live-check|audit\.mjs|bench\.mjs/.test(e))) problems.push(at + ": " + c.verified + " needs a real-runtime run as evidence");
    if (c.implemented !== "none" && c.implemented !== "architecture" && !c.via.length) problems.push(at + ": implemented but does not say what it rests on (via)");
    if (["partial", "yes"].includes(c.implemented) && !c.gap && c.implemented === "partial") problems.push(at + ": partial must say what is missing (gap)");
    // never above what the tool registry allows
    const tools = c.via.filter((v) => v.startsWith("tool:")).map((v) => v.slice(5));
    for (const n of tools) if (!(n in toolStates)) problems.push(at + ": unknown tool " + n);
    const known = tools.filter((n) => n in toolStates);
    if (known.length && known.every((n) => toolStates[n] === "not_built") && !["none", "architecture"].includes(c.implemented) && !c.via.some((v) => v.startsWith("route:") || v.startsWith("app:"))) problems.push(at + ": every tool it rests on is not built, so it cannot be " + c.implemented);
    for (const e of c.evidence) if (!/^(manual|live):/i.test(e)) { const file = e.replace(/\s*\(.*$/, "").trim(); if (fileExists && !fileExists(file)) problems.push(at + ": evidence file not found: " + file); }
  }
  return problems;
}

// Plain language for every capability, so "Target: true" can never be misread as "Noria has this". The three facts are shown as words.
const IMPL_TEXT = { none: "Not built", architecture: "Designed only", foundation: "Foundation built, not usable yet", partial: "Usable, with limits", yes: "Built and usable" };
const VER_TEXT = { none: "Not tested", component: "Parts tested in isolation", read_only: "Exercised in the real runtime, reading only", real_runtime: "Exercised end to end in the real environment" };
export function explainCapability(c) {
  const has = ["partial", "yes"].includes(c.implemented);
  return {
    target_capability: "Target capability: what Noria is meant to become. This is NOT a claim that Noria has it.",
    implemented: IMPL_TEXT[c.implemented],
    verified: VER_TEXT[c.verified],
    today: has ? "Noria has this today" + (c.gap ? ", with limits: " + c.gap : ".") : "Noria does NOT have this today" + (c.implemented === "none" ? "." : c.implemented === "architecture" ? " (only designed)." : " (a foundation exists but it is not usable yet)."),
  };
}
export function explainFamilies(families) { return families.map((f) => ({ ...f, capabilities: f.capabilities.map((c) => ({ ...c, plain: explainCapability(c) })) })); }
// The summary shown to the owner: how many of the target capabilities are implemented, and how many verified, at each level.
export function summarizeFamilies(families) {
  const all = families.flatMap((f) => f.capabilities), by = (key, levels) => Object.fromEntries(levels.map((l) => [l, all.filter((c) => c[key] === l).length]));
  return { families: families.length, capabilities: all.length, target: all.length, implemented: by("implemented", IMPLEMENTED), verified: by("verified", VERIFIED),
    per_family: families.map((f) => ({ id: f.id, name: f.name, capabilities: f.capabilities.length, implemented_usable: f.capabilities.filter((c) => ["partial", "yes"].includes(c.implemented)).length, verified_any: f.capabilities.filter((c) => c.verified !== "none").length })),
    meaning: "Target is what Noria is meant to become. Implemented is what has been built. Verified is what has been tested for real. The tests measure the machine; they do not define what Noria can do." };
}
